In [ ]:
import numpy as np

#1 create a 1D array of numbers from 0-9

array = np.array([1,2,3,4,5,6,7,8,9])

print(array)



[1 2 3 4 5 6 7 8 9]


In [ ]:
#2 create a 3x3 array of boolean value trues

array2 = np.array([[1,2,3,], [4,5,6], [7,8,9]])

print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3 extract all odd numbers from array of 1-10

slice = np.array([1,2,3,4,5,6,7,8,9,10])

print(slice[0:10:2]) # from 0 to 10 in sections of 2

[1 3 5 7 9]


In [ ]:
#havent a clue hoe to start no 4!!!!

In [ ]:
#5 convert a 1D array to a 2D array with 2 rows
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArray = array1.reshape(2, 6)

print(newArray)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
#6

import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(10, 19).reshape(3, 3)
c = np.dot(a, b)
print(c)

total_sum =np.sum(c)
print(total_sum)



[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944
